{"name": "test_wrong_email_wrong_password", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = check_account('tamarsamara', 'tttttt')", "trace": "@pytest.mark.failed\n    def test_wrong_email_wrong_password():\n        \"\"\"\n        Check valid email and wrong password\n        Error message: \"Authentication failed.\"\n        failed\n        \"\"\"\n        logging.info(\"Successful Login\")\n        logging.warning(\"Error message: Authentication failed.\")\n>       assert check_account(\"tamarsamara\", \"tttttt\")\nE       AssertionError: assert False\nE        +  where False = check_account('tamarsamara', 'tttttt')\n\ntests\\test_page_authentication.py:78: AssertionError"}, "description": "\n    Check valid email and wrong password\n    Error message: \"Authentication failed.\"\n    failed\n    ", "attachments": [{"name": "log", "source": "889ce377-607f-49bc-a860-e3eabf4f0980-attachment.txt", "type": "text/plain"}], "start": 1660854134673, "stop": 1660854177606, "uuid": "c983fc3a-7423-441d-9025-9d97603e7aa3", "historyId": "50520968954bd5664b09d3d2cad67d2e", "testCaseId": "2d1ff229532ee4da75735cd368b6eee3", "fullName": "tests.test_page_authentication#test_wrong_email_wrong_password", "labels": [{"name": "tag", "value": "failed"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_page_authentication"}, {"name": "host", "value": "tamar1"}, {"name": "thread", "value": "25568-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_page_authentication"}]}